using Certify.Management;
using Certify.Models;
using Certify.Models.Config;
using Plugin.DeploymentTasks.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Certify.Providers.DeploymentTasks
{
    public class UpdatePortBinding : IDeploymentTaskProvider
    {
        public static DeploymentProviderDefinition Definition { get; }
        public DeploymentProviderDefinition GetDefinition(DeploymentProviderDefinition currentDefinition = null) => (currentDefinition ?? Definition);

        private const string SCRIPT_NAME = "UpdatePortBinding.ps1";

        static UpdatePortBinding()
        {
            Definition = new DeploymentProviderDefinition
            {
                Id = "Certify.Providers.DeploymentTasks.UpdatePortBinding",
                Title = "Update Port Binding",
                DefaultTitle = "Update Port Binding",
                IsExperimental = true,
                UsageType = DeploymentProviderUsage.PostRequest,
                SupportedContexts = DeploymentContextType.LocalAsService,
                Description = "Uses netsh to update a IP:port certificate binding",
                ProviderParameters = new List<ProviderParameter>
                {
                      new ProviderParameter{ Key="ip", Name="IP", IsRequired=true, IsCredential=false, Value="0.0.0.0"},
                      new ProviderParameter{ Key="port", Name="Port", IsRequired=true, IsCredential=false},
                      new ProviderParameter{ Key="appid", Name="App Id (Guid)", IsRequired=true, IsCredential=false, Description="(optional app id)"},
                }
            };
        }

        public async Task<List<ActionResult>> Execute(DeploymentTaskExecutionParams execParams)
        {

            var validation = await Validate(execParams);

            if (validation.Any())
            {
                return validation;
            }

            var script = Helpers.ReadStringResource(SCRIPT_NAME);

            var certRequest = execParams.Subject as CertificateRequestResult;

            execParams.Log?.Information("Executing command via PowerShell");

            var ip = execParams.Settings.Parameters.FirstOrDefault(p => p.Key == "ip")?.Value;
            var port = execParams.Settings.Parameters.FirstOrDefault(p => p.Key == "port")?.Value;
            var appid = execParams.Settings.Parameters.FirstOrDefault(p => p.Key == "appid")?.Value;

            var parameters = new Dictionary<string, object>
            {
                { "ip", ip },
                { "port", port },
                { "appid", appid }
            };

            var scriptResult = await PowerShellManager.RunScript(execParams.Context.PowershellExecutionPolicy, certRequest, parameters: parameters, scriptContent: script, credentials: execParams.Credentials);

            return new List<ActionResult> { scriptResult };
        }

        public async Task<List<ActionResult>> Validate(DeploymentTaskExecutionParams execParams)
        {
            var results = new List<ActionResult>();

            if (string.IsNullOrEmpty(execParams.Settings.Parameters.FirstOrDefault(p => p.Key == "ip")?.Value))
            {
                results.Add(new ActionResult("An IP is required. Use 0.0.0.0 to catch all.", false));
            }

            if (string.IsNullOrEmpty(execParams.Settings.Parameters.FirstOrDefault(p => p.Key == "port")?.Value))
            {
                results.Add(new ActionResult("An Port number is required.", false));
            }

            var guid = execParams.Settings.Parameters.FirstOrDefault(p => p.Key == "guid")?.Value;

            if (guid != null && !Guid.TryParse(guid, out var parsedGuid))
            {
                results.Add(new ActionResult("Invalid AppID (GUID). Leave blank to use an autogenerated guid.", false));
            }

            return await Task.FromResult(results);
        }

    }
}
