<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <AssemblyName>Plugin.CertificateManagers.Core</AssemblyName>
        <RootNamespace>Certify.Plugin.CertificateManagers</RootNamespace>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Bcl.Cryptography" Version="10.0.0-rc.2.25502.107" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\..\certify\src\Certify.Models\Certify.Models.csproj" />
        <ProjectReference Include="..\..\..\..\certify\src\Certify.Shared\Certify.Shared.Core.csproj" />
    </ItemGroup>

</Project>
